# Generated by Django 4.1.5 on 2023-01-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_verified_email_emailvirification"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmailVirification",
            new_name="EmailVerification",
        ),
    ]
