# Generated by Django 4.1.5 on 2023-01-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_basket"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "категория", "verbose_name_plural": "Категории"},
        ),
    ]
